---
title: Cocktails analysis
author: Xuxin Zhang
date: '2020-09-21'
slug: cocktails-analysis
categories:
  - R project
tags:
  - data visualization
  - Rshiny
subtitle: ''
summary: ''
authors: []
lastmod: '2020-09-21T12:00:34+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
output:
  blogdown::html_page:
    toc: false
runtime: shiny
projects: []
---

```{r,warning=FALSE, message=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
theme_set(theme_light())
cocktails <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/cocktails.csv')
boston_cocktails <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv')

```

```{r}
library(stringr)

cocktails%>%distinct(drink)

boston_cocktails%>%distinct(name)

boston_cocktails%>%count(category)
```

```{r}
# find out how many types of fractions are there
boston_cocktails%>%
  mutate(measure = str_remove(measure, "oz"))%>%
  separate_rows(measure, sep = " ")%>%
  mutate(frac = str_detect(measure, "/"))%>%
  filter(frac==TRUE)%>%count(measure)

# convert the limited types of fraction into digits.
boston_cocktails_clean<-boston_cocktails%>%
  mutate(measure = str_remove(measure, "oz"))%>%
  separate_rows(measure, sep = " ")%>%
  mutate(measure= case_when(measure == "1/2"~0.5,
                            measure == "1/3"~round(1/3,3),
                            measure == "1/4"~0.25,
                            measure == "2/3"~round(2/3,3),
                            measure == "3/4"~0.75,
                            TRUE~as.numeric(measure)))%>%
  filter(!is.na(measure))%>%
  group_by(name,category,ingredient_number,ingredient)%>%
  summarise(measure = sum(measure))

boston_cocktails_clean
```


<iframe src="https://xuxinzhang.shinyapps.io/cocktails_shiny_app/?_ga=2.77218197.1061771204.1600663501-1747614968.1600663501"></iframe>


